const PRODUCTS = [
  {
    "id": 1,
    "sku": "INV-001",
    "name": "MAE PLOY SWEET CHILLI SAUCE 920G",
    "category": "Grocery",
    "subcategory": "Sauce",
    "price": 3.99,
    "offer_price": 1.99,
    "pack": "920G",
    "stock": "In Stock",
    "stock_qty": 12,
    "badge": "Special Offer",
    "emoji": "cart",
    "description": "920G pack.",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ63q2qToqbYH4E_DfhOQtWXXXy-ppwKjxBJQ&s",
    "invoice_amount": 7.98,
    "invoice_qty": 2,
    "units_per_case": 1
  },
  {
    "id": 2,
    "sku": "INV-002",
    "name": "MAGGI COCONUT POWDER 300G",
    "category": "Grocery",
    "subcategory": "Coconut",
    "price": 4.99,
    "offer_price": null,
    "pack": "300G",
    "stock": "In Stock",
    "stock_qty": 6,
    "badge": "",
    "emoji": "cart",
    "description": "300G pack.",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRl6SuK22yvKtwQHa21apLnA3L_geTae6uYgQ&s",
    "invoice_amount": 19.99,
    "invoice_qty": 1,
    "units_per_case": 6
  },
  {
    "id": 3,
    "sku": "INV-003",
    "name": "KTC RED KIDNEY BEANS 400G",
    "category": "Grocery",
    "subcategory": "Beans",
    "price": 0.99,
    "offer_price": 0.79,
    "pack": "400G",
    "stock": "In Stock",
    "stock_qty": 12,
    "badge": "Special Offer",
    "emoji": "cart",
    "description": "400G pack.",
    "image": "https://assets.sainsburys-groceries.co.uk/gol/7953192/1/640x640.jpg",
    "invoice_amount": 5.99,
    "invoice_qty": 1,
    "units_per_case": 12
  },
  {
    "id": 4,
    "sku": "INV-004",
    "name": "KTC BLACK EYE BEANS CAN 400G",
    "category": "Grocery",
    "subcategory": "Beans",
    "price": 0.99,
    "offer_price": 0.79,
    "pack": "400G",
    "stock": "In Stock",
    "stock_qty": 12,
    "badge": "Special Offer",
    "emoji": "cart",
    "description": "400G pack.",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0b4t2nFoNgCNMfJGFvfg5ccRvppo0WMlQvQ&s",
    "invoice_amount": 5.39,
    "invoice_qty": 1,
    "units_per_case": 12
  },
  {
    "id": 5,
    "sku": "INV-005",
    "name": "KTC ROSE WATER 190ML",
    "category": "Grocery",
    "subcategory": "Rose Water",
    "price": 1.99,
    "offer_price": 0.99,
    "pack": "190ML",
    "stock": "In Stock",
    "stock_qty": 12,
    "badge": "Special Offer",
    "emoji": "cart",
    "description": "190ML pack.",
    "image": "https://ezebra.co.uk/hpeciai/939a33b21aa7616b8d7a54630b8a8e8e/eng_pl_KTC-ROSE-WATER-NATURAL-ROSE-WATER-190ML-64012_1.webp",
    "invoice_amount": 6.19,
    "invoice_qty": 1,
    "units_per_case": 12
  },
  {
    "id": 6,
    "sku": "INV-006",
    "name": "TRS DHANIA WHOLE INDORI 250G",
    "category": "Grocery",
    "subcategory": "Spices",
    "price": 2.19,
    "offer_price": 1.49,
    "pack": "250G",
    "stock": "In Stock",
    "stock_qty": 10,
    "badge": "Special Offer",
    "emoji": "cart",
    "description": "250G pack.",
    "image": "https://koodai.co.uk/cdn/shop/products/L4110_-_WHOLE_DHANIA_250G_720x.jpg?v=1698878652",
    "invoice_amount": 10.15,
    "invoice_qty": 1,
    "units_per_case": 10
  },
  {
    "id": 7,
    "sku": "INV-007",
    "name": "TRS WHOLE PEAS YELLOW 2KG",
    "category": "Grocery",
    "subcategory": "Dals & Pulses",
    "price": 3.49,
    "offer_price": null,
    "pack": "2KG",
    "stock": "In Stock",
    "stock_qty": 6,
    "badge": "",
    "emoji": "cart",
    "description": "2KG pack.",
    "image": "https://www.trsfood.com/wp-content/uploads/2024/02/Whole-Yellow-Peas-500g_4800x4800-Background-Removed-1200x1200.png",
    "invoice_amount": 14.95,
    "invoice_qty": 1,
    "units_per_case": 6
  },
  {
    "id": 8,
    "sku": "INV-008",
    "name": "TRS BLACK EYE BEANS 500G",
    "category": "Grocery",
    "subcategory": "Beans",
    "price": 1.89,
    "offer_price": null,
    "pack": "500G",
    "stock": "In Stock",
    "stock_qty": 20,
    "badge": "",
    "emoji": "cart",
    "description": "500G pack.",
    "image": "https://asdagroceries.scene7.com/is/image/asdagroceries/5017689000332",
    "invoice_amount": 26.99,
    "invoice_qty": 1,
    "units_per_case": 20
  },
  {
    "id": 9,
    "sku": "INV-009",
    "name": "TRS MUNG WHOLE 2KG",
    "category": "Grocery",
    "subcategory": "Dals & Pulses",
    "price": 4.19,
    "offer_price": null,
    "pack": "2KG",
    "stock": "In Stock",
    "stock_qty": 6,
    "badge": "",
    "emoji": "cart",
    "description": "2KG pack.",
    "image": "https://foodbazaar.co.uk/cdn/shop/files/51eBB3fl-2L._SR600_315_PIWhiteStrip_BottomLeft_0_35_SCLZZZZZZZ_FMpng_BG255_255_255_1.png?v=1716471288",
    "invoice_amount": 17.95,
    "invoice_qty": 1,
    "units_per_case": 6
  },
  {
    "id": 10,
    "sku": "INV-010",
    "name": "TRS METHI SEEDS 300G",
    "category": "Grocery",
    "subcategory": "Spices",
    "price": 1.69,
    "offer_price": null,
    "pack": "300G",
    "stock": "In Stock",
    "stock_qty": 10,
    "badge": "",
    "emoji": "cart",
    "description": "300G pack.",
    "image": "https://i.ebayimg.com/images/g/-2oAAeSwPfRn3Ale/s-l400.jpg",
    "invoice_amount": 9.59,
    "invoice_qty": 1,
    "units_per_case": 10
  },
  {
    "id": 11,
    "sku": "INV-011",
    "name": "TRS CANNED BOILED CHICKPEAS 2.5KG",
    "category": "Grocery",
    "subcategory": "Beans",
    "price": 3.99,
    "offer_price": null,
    "pack": "2.5KG",
    "stock": "In Stock",
    "stock_qty": 6,
    "badge": "",
    "emoji": "cart",
    "description": "2.5KG pack.",
    "image": "https://londongrocery.net/cdn/shop/products/trsboiledchkp625kg_600x.png?v=1680552654",
    "invoice_amount": 13.99,
    "invoice_qty": 1,
    "units_per_case": 6
  },
  {
    "id": 12,
    "sku": "INV-012",
    "name": "TRS POPPY SEED WHITE 100G",
    "category": "Grocery",
    "subcategory": "Spices",
    "price": 1.99,
    "offer_price": null,
    "pack": "100G",
    "stock": "In Stock",
    "stock_qty": 20,
    "badge": "",
    "emoji": "cart",
    "description": "100G pack.",
    "image": "https://i.ebayimg.com/images/g/D9MAAeSwMNtn2nCA/s-l400.jpg",
    "invoice_amount": 17.75,
    "invoice_qty": 1,
    "units_per_case": 20
  },
  {
    "id": 13,
    "sku": "INV-013",
    "name": "TRS BLACK PEPPER WHOLE 100G",
    "category": "Grocery",
    "subcategory": "Spices",
    "price": 2.29,
    "offer_price": null,
    "pack": "100G",
    "stock": "In Stock",
    "stock_qty": 20,
    "badge": "",
    "emoji": "cart",
    "description": "100G pack.",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKvl1q4jRGfuzL35r832efu39Aky2vAQbJYg&s",
    "invoice_amount": 31.65,
    "invoice_qty": 1,
    "units_per_case": 20
  },
  {
    "id": 14,
    "sku": "INV-014",
    "name": "TRS CLOVES WHOLE 50G",
    "category": "Grocery",
    "subcategory": "Spices",
    "price": 1.99,
    "offer_price": null,
    "pack": "50G",
    "stock": "In Stock",
    "stock_qty": 20,
    "badge": "",
    "emoji": "cart",
    "description": "50G pack.",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhofA_bXqD98luzmA4eG9X4atC3BL26-OjUg&s",
    "invoice_amount": 24.59,
    "invoice_qty": 1,
    "units_per_case": 20
  },
  {
    "id": 15,
    "sku": "INV-015",
    "name": "TRS CHANA DALL 1KG",
    "category": "Grocery",
    "subcategory": "Dals & Pulses",
    "price": 2.49,
    "offer_price": null,
    "pack": "1KG",
    "stock": "In Stock",
    "stock_qty": 10,
    "badge": "",
    "emoji": "cart",
    "description": "1KG pack.",
    "image": "https://keysworldfoodstore.com/wp-content/uploads/2025/06/TRS-Chana-Dal-1kg.jpg",
    "invoice_amount": 17.35,
    "invoice_qty": 1,
    "units_per_case": 10
  },
  {
    "id": 16,
    "sku": "INV-016",
    "name": "TRS LENTILS RED MASOOR DALL 1KG",
    "category": "Grocery",
    "subcategory": "Dals & Pulses",
    "price": 2.49,
    "offer_price": null,
    "pack": "1KG",
    "stock": "In Stock",
    "stock_qty": 10,
    "badge": "",
    "emoji": "cart",
    "description": "1KG pack.",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTYNw_W5Xbm0SKe2XEQgMz8L2rt5A6NmU34g&s",
    "invoice_amount": 15.25,
    "invoice_qty": 1,
    "units_per_case": 10
  },
  {
    "id": 17,
    "sku": "INV-017",
    "name": "TRS DHANIA POWDER INDORI 400G",
    "category": "Grocery",
    "subcategory": "Spices",
    "price": 1.99,
    "offer_price": null,
    "pack": "400G",
    "stock": "In Stock",
    "stock_qty": 10,
    "badge": "",
    "emoji": "cart",
    "description": "400G pack.",
    "image": "https://m.media-amazon.com/images/I/51uUwK5WcYL.jpg",
    "invoice_amount": 12.75,
    "invoice_qty": 1,
    "units_per_case": 10
  },
  {
    "id": 18,
    "sku": "INV-018",
    "name": "AASHIRVAAD MULTIGRAIN ATTA 2KG",
    "category": "Grocery",
    "subcategory": "Flour & Atta",
    "price": 5.99,
    "offer_price": null,
    "pack": "2KG",
    "stock": "In Stock",
    "stock_qty": 10,
    "badge": "",
    "emoji": "cart",
    "description": "2KG pack.",
    "image": "https://m.media-amazon.com/images/I/51XyIXKJgFL.jpg",
    "invoice_amount": 37.5,
    "invoice_qty": 1,
    "units_per_case": 10
  },
  {
    "id": 19,
    "sku": "INV-019",
    "name": "AASHIRVAAD WHOLE WHEAT ATTA 2KG",
    "category": "Grocery",
    "subcategory": "Flour & Atta",
    "price": 4.99,
    "offer_price": null,
    "pack": "2KG",
    "stock": "In Stock",
    "stock_qty": 10,
    "badge": "",
    "emoji": "cart",
    "description": "2KG pack.",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1ZWEyXM0famqNhCwb2q7rmalR1ht201To7Q&s",
    "invoice_amount": 33,
    "invoice_qty": 1,
    "units_per_case": 10
  },
  {
    "id": 20,
    "sku": "INV-020",
    "name": "NIDO MILK 900G",
    "category": "Grocery",
    "subcategory": "Milk Powder",
    "price": 12.99,
    "offer_price": 11.99,
    "pack": "900G",
    "stock": "In Stock",
    "stock_qty": 6,
    "badge": "Special Offer",
    "emoji": "cart",
    "description": "900G pack.",
    "image": "https://assets.sainsburys-groceries.co.uk/gol/8033837/1/640x640.jpg",
    "invoice_amount": 49.99,
    "invoice_qty": 1,
    "units_per_case": 6
  },
  {
    "id": 21,
    "sku": "INV-021",
    "name": "NIRU ROASTED RED RICE FLOUR CANADA 3.6KG",
    "category": "Grocery",
    "subcategory": "Flour & Atta",
    "price": 11.99,
    "offer_price": null,
    "pack": "3.6KG",
    "stock": "In Stock",
    "stock_qty": 6,
    "badge": "",
    "emoji": "cart",
    "description": "3.6KG pack.",
    "image": "https://allibhavan.com/cdn/shop/files/niru-roasted-red-rice-flour-2kg-alli-bhavan-769748.png?v=1722838384&width=1800",
    "invoice_amount": 51,
    "invoice_qty": 1,
    "units_per_case": 6
  },
  {
    "id": 22,
    "sku": "INV-022",
    "name": "NIRU OFFER PUTTU FLOUR 3.6KG",
    "category": "Grocery",
    "subcategory": "Flour & Atta",
    "price": 7.99,
    "offer_price": null,
    "pack": "3.6KG",
    "stock": "In Stock",
    "stock_qty": 6,
    "badge": "",
    "emoji": "cart",
    "description": "3.6KG pack.",
    "image": "data:image/svg+xml;charset=UTF-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22500%22%20height%3D%22500%22%20viewBox%3D%220%200%20500%20500%22%3E%0A%20%20%3Crect%20width%3D%22500%22%20height%3D%22500%22%20rx%3D%2242%22%20fill%3D%22%23fff8eb%22%2F%3E%0A%20%20%3Crect%20x%3D%2232%22%20y%3D%2232%22%20width%3D%22436%22%20height%3D%22436%22%20rx%3D%2234%22%20fill%3D%22%23ffffff%22%20stroke%3D%22%23ecd8b8%22%20stroke-width%3D%226%22%2F%3E%0A%20%20%3Ccircle%20cx%3D%22250%22%20cy%3D%22180%22%20r%3D%2270%22%20fill%3D%22%230b7a3b%22%20opacity%3D%22.12%22%2F%3E%0A%20%20%3Cpath%20d%3D%22M177%20252h146l-18%2092H195l-18-92Z%22%20fill%3D%22%230b7a3b%22%2F%3E%0A%20%20%3Cpath%20d%3D%22M205%20252c0-34%2020-62%2045-62s45%2028%2045%2062%22%20fill%3D%22none%22%20stroke%3D%22%23d4141d%22%20stroke-width%3D%2218%22%20stroke-linecap%3D%22round%22%2F%3E%0A%20%20%3Ctext%20x%3D%22250%22%20y%3D%22392%22%20text-anchor%3D%22middle%22%20font-family%3D%22Arial%2C%20Helvetica%2C%20sans-serif%22%20font-size%3D%2234%22%20font-weight%3D%22900%22%20fill%3D%22%23d4141d%22%3ECHENNAI%3C%2Ftext%3E%0A%20%20%3Ctext%20x%3D%22250%22%20y%3D%22430%22%20text-anchor%3D%22middle%22%20font-family%3D%22Arial%2C%20Helvetica%2C%20sans-serif%22%20font-size%3D%2232%22%20font-weight%3D%22900%22%20fill%3D%22%230b7a3b%22%3EEXPRESS%3C%2Ftext%3E%0A%20%20%3Ctext%20x%3D%22250%22%20y%3D%22462%22%20text-anchor%3D%22middle%22%20font-family%3D%22Arial%2C%20Helvetica%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22700%22%20fill%3D%22%23555%22%3EFOOD%20%26amp%3B%20GROCERY%3C%2Ftext%3E%0A%3C%2Fsvg%3E%0A",
    "invoice_amount": 33.6,
    "invoice_qty": 1,
    "units_per_case": 6
  },
  {
    "id": 23,
    "sku": "INV-023",
    "name": "NIRU STEAMED ATTAH FLOUR 1KG",
    "category": "Grocery",
    "subcategory": "Flour & Atta",
    "price": 2.79,
    "offer_price": null,
    "pack": "1KG",
    "stock": "In Stock",
    "stock_qty": 20,
    "badge": "",
    "emoji": "cart",
    "description": "1KG pack.",
    "image": "https://malabardirect.com/cdn/shop/files/Photoroom-20240508_155754_1200x630.png?v=1716164779",
    "invoice_amount": 39.8,
    "invoice_qty": 1,
    "units_per_case": 20
  },
  {
    "id": 24,
    "sku": "INV-024",
    "name": "SHANKAR CHANA DHALL 2KG UPM",
    "category": "Grocery",
    "subcategory": "Dals & Pulses",
    "price": 3.5,
    "offer_price": null,
    "pack": "2KG",
    "stock": "In Stock",
    "stock_qty": 6,
    "badge": "",
    "emoji": "cart",
    "description": "2KG pack.",
    "image": "https://www.exoticestore.com/cdn/shop/files/Shankar_Channa_Dhal_2Kg.jpg?v=1750428149&width=1600",
    "invoice_amount": 15,
    "invoice_qty": 1,
    "units_per_case": 6
  },
  {
    "id": 25,
    "sku": "INV-025",
    "name": "SHANKAR UNROASTED WHITE RICE FLOUR 2KG",
    "category": "Grocery",
    "subcategory": "Flour & Atta",
    "price": 2.99,
    "offer_price": null,
    "pack": "2KG",
    "stock": "In Stock",
    "stock_qty": 8,
    "badge": "",
    "emoji": "cart",
    "description": "2KG pack.",
    "image": "https://allibhavan.com/cdn/shop/files/shankar-white-rice-flour-2kg-alli-bhavan-548734.jpg?v=1731156314&width=1080",
    "invoice_amount": 17,
    "invoice_qty": 1,
    "units_per_case": 8
  },
  {
    "id": 26,
    "sku": "INV-026",
    "name": "SURYA PUTTU FLOUR RED 1KG",
    "category": "Grocery",
    "subcategory": "Flour & Atta",
    "price": 2.23,
    "offer_price": null,
    "pack": "1KG",
    "stock": "In Stock",
    "stock_qty": 20,
    "badge": "",
    "emoji": "cart",
    "description": "1KG pack.",
    "image": "https://d2lhwe7okuon6r.cloudfront.net/media/productimages/148/67/652467.png",
    "invoice_amount": 31.8,
    "invoice_qty": 1,
    "units_per_case": 20
  },
  {
    "id": 27,
    "sku": "INV-027",
    "name": "SURYA ROASTED RED RICE FLOUR 1KG",
    "category": "Grocery",
    "subcategory": "Flour & Atta",
    "price": 2.23,
    "offer_price": null,
    "pack": "1KG",
    "stock": "In Stock",
    "stock_qty": 20,
    "badge": "",
    "emoji": "cart",
    "description": "1KG pack.",
    "image": "https://www.indianspiceshops.co.uk/image/cache/catalog/Web-Images/Product/2nd-batch/SURYAA-Puttu-Flour-Red-1kg-250x250.jpg",
    "invoice_amount": 31.8,
    "invoice_qty": 1,
    "units_per_case": 20
  },
  {
    "id": 28,
    "sku": "INV-028",
    "name": "SURYA STRINGHOPPER FLOUR RED 1KG",
    "category": "Grocery",
    "subcategory": "Flour & Atta",
    "price": 2.29,
    "offer_price": null,
    "pack": "1KG",
    "stock": "In Stock",
    "stock_qty": 20,
    "badge": "",
    "emoji": "cart",
    "description": "1KG pack.",
    "image": "https://www.lakshmistores.com/cdn/shop/products/suryaarstringhoper_625a7e14-a6ba-4cff-a451-7fbf4236f275.jpg?v=1639165373",
    "invoice_amount": 31.8,
    "invoice_qty": 1,
    "units_per_case": 20
  },
  {
    "id": 29,
    "sku": "INV-029",
    "name": "SURYA STRINGHOPPER FLOUR WHITE 1KG",
    "category": "Grocery",
    "subcategory": "Flour & Atta",
    "price": 2.23,
    "offer_price": null,
    "pack": "1KG",
    "stock": "In Stock",
    "stock_qty": 20,
    "badge": "",
    "emoji": "cart",
    "description": "1KG pack.",
    "image": "https://www.lakshmistores.com/cdn/shop/products/SURYAA_STRING_HOPPER_FLOUR_RED_-_1KG_68cd9c04-0af8-4130-b1a0-8671eb9291db.jpg?v=1639165371&width=1780",
    "invoice_amount": 31.8,
    "invoice_qty": 1,
    "units_per_case": 20
  },
  {
    "id": 30,
    "sku": "INV-030",
    "name": "SURYA STEAMED WHEAT FLOUR 1KG",
    "category": "Grocery",
    "subcategory": "Flour & Atta",
    "price": 2.79,
    "offer_price": null,
    "pack": "1KG",
    "stock": "In Stock",
    "stock_qty": 20,
    "badge": "",
    "emoji": "cart",
    "description": "1KG pack.",
    "image": "https://d2lhwe7okuon6r.cloudfront.net/media/productimages/148/77/652477.png",
    "invoice_amount": 39.8,
    "invoice_qty": 1,
    "units_per_case": 20
  },
  {
    "id": 31,
    "sku": "INV-031",
    "name": "TRS GARAM MASALA POWDER 400G",
    "category": "Grocery",
    "subcategory": "Masala & Spices",
    "price": 3.64,
    "offer_price": null,
    "pack": "400G",
    "stock": "In Stock",
    "stock_qty": 10,
    "badge": "",
    "emoji": "cart",
    "description": "400G pack.",
    "image": "https://m.media-amazon.com/images/I/51VoCdlAVvL._AC_UF350,350_QL80_.jpg",
    "invoice_amount": 25.99,
    "invoice_qty": 1,
    "units_per_case": 10
  },
  {
    "id": 32,
    "sku": "INV-032",
    "name": "TRS MUSTARD SEEDS 100G",
    "category": "Grocery",
    "subcategory": "Spices",
    "price": 0.51,
    "offer_price": null,
    "pack": "100G",
    "stock": "In Stock",
    "stock_qty": 20,
    "badge": "",
    "emoji": "cart",
    "description": "100G pack.",
    "image": "https://www.spicebazar.uk/cdn/shop/products/trs-brown-mustard-seeds-100g.jpg?v=1596649882",
    "invoice_amount": 7.25,
    "invoice_qty": 1,
    "units_per_case": 20
  },
  {
    "id": 33,
    "sku": "INV-033",
    "name": "TRS KALA CHANA BROWN 1KG",
    "category": "Grocery",
    "subcategory": "Dals & Pulses",
    "price": 2.47,
    "offer_price": null,
    "pack": "1KG",
    "stock": "In Stock",
    "stock_qty": 10,
    "badge": "",
    "emoji": "cart",
    "description": "1KG pack.",
    "image": "https://indus-valley.de/assets/uploads/5ab068ee4ed7eb8ba5125bee73074a9f.jpeg",
    "invoice_amount": 17.65,
    "invoice_qty": 1,
    "units_per_case": 10
  },
  {
    "id": 34,
    "sku": "INV-034",
    "name": "TRS KALA NAMAK BLACK SALT POWDER 100G",
    "category": "Grocery",
    "subcategory": "Spices",
    "price": 0.59,
    "offer_price": null,
    "pack": "100G",
    "stock": "In Stock",
    "stock_qty": 20,
    "badge": "",
    "emoji": "cart",
    "description": "100G pack.",
    "image": "https://www.sujash.co.uk/cdn/shop/files/TRSBlacksalt-1.jpg?v=1727783314",
    "invoice_amount": 5.99,
    "invoice_qty": 1,
    "units_per_case": 20
  },
  {
    "id": 35,
    "sku": "INV-035",
    "name": "TRS RAGI FLOUR 1KG",
    "category": "Grocery",
    "subcategory": "Flour & Atta",
    "price": 2.47,
    "offer_price": null,
    "pack": "1KG",
    "stock": "In Stock",
    "stock_qty": 10,
    "badge": "",
    "emoji": "cart",
    "description": "1KG pack.",
    "image": "https://m.media-amazon.com/images/I/61lZ5JdQCEL._AC_UF350,350_QL80_.jpg",
    "invoice_amount": 17.65,
    "invoice_qty": 1,
    "units_per_case": 10
  },
  {
    "id": 36,
    "sku": "INV-036",
    "name": "TRS FLAKE RICE THICK PAWA 1KG",
    "category": "Grocery",
    "subcategory": "Rice & Flakes",
    "price": 2.69,
    "offer_price": null,
    "pack": "1KG",
    "stock": "In Stock",
    "stock_qty": 6,
    "badge": "",
    "emoji": "cart",
    "description": "1KG pack.",
    "image": "https://www.sujash.co.uk/cdn/shop/files/IMG_1433.jpg?v=1741741341",
    "invoice_amount": 11.19,
    "invoice_qty": 1,
    "units_per_case": 6
  },
  {
    "id": 37,
    "sku": "INV-037",
    "name": "TRS MUNG DALL 2KG",
    "category": "Grocery",
    "subcategory": "Dals & Pulses",
    "price": 5.49,
    "offer_price": null,
    "pack": "2KG",
    "stock": "In Stock",
    "stock_qty": 6,
    "badge": "",
    "emoji": "cart",
    "description": "2KG pack.",
    "image": "https://www.exoticestore.com/cdn/shop/products/TRSMungDal2kg.jpg?v=1590538055",
    "invoice_amount": 21.49,
    "invoice_qty": 1,
    "units_per_case": 6
  },
  {
    "id": 38,
    "sku": "INV-038",
    "name": "HEERA TOOR DAL OILY MALAWI 2KG",
    "category": "Grocery",
    "subcategory": "Dals & Pulses",
    "price": 4.66,
    "offer_price": null,
    "pack": "2KG",
    "stock": "In Stock",
    "stock_qty": 6,
    "badge": "",
    "emoji": "cart",
    "description": "2KG pack.",
    "image": "https://bazaar-foods.co.uk/cdn/shop/products/heera-toor-dall-oily-2kg.jpg?v=1649240359",
    "invoice_amount": 19.99,
    "invoice_qty": 1,
    "units_per_case": 6
  },
  {
    "id": 39,
    "sku": "INV-039",
    "name": "HEERA CUMIN POWDER JEERA 100G",
    "category": "Grocery",
    "subcategory": "Spices",
    "price": 1.59,
    "offer_price": null,
    "pack": "100G",
    "stock": "In Stock",
    "stock_qty": 20,
    "badge": "",
    "emoji": "cart",
    "description": "100G pack.",
    "image": "https://desime.co.uk/cdn/shop/files/1279_8.jpg?v=1699445124",
    "invoice_amount": 17.55,
    "invoice_qty": 1,
    "units_per_case": 20
  },
  {
    "id": 40,
    "sku": "INV-040",
    "name": "HEERA CUMIN WHOLE JEERA 300G",
    "category": "Grocery",
    "subcategory": "Spices",
    "price": 3.34,
    "offer_price": null,
    "pack": "300G",
    "stock": "In Stock",
    "stock_qty": 10,
    "badge": "",
    "emoji": "cart",
    "description": "300G pack.",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7jBJ2iXjVyY-qHIZ6S_SqPGj3QIKOKiDw9A&s",
    "invoice_amount": 23.89,
    "invoice_qty": 1,
    "units_per_case": 10
  },
  {
    "id": 41,
    "sku": "INV-041",
    "name": "HEERA TURMERIC POWDER HALDI 400G",
    "category": "Grocery",
    "subcategory": "Spices",
    "price": 2.15,
    "offer_price": null,
    "pack": "400G",
    "stock": "In Stock",
    "stock_qty": 10,
    "badge": "",
    "emoji": "cart",
    "description": "400G pack.",
    "image": "https://halalo.co.uk/images/detailed/70/url_uploaded_file_177414721869bf5693266e0.webp",
    "invoice_amount": 15.39,
    "invoice_qty": 1,
    "units_per_case": 10
  },
  {
    "id": 42,
    "sku": "INV-042",
    "name": "MOM MADE METHI PARATHA 400G",
    "category": "Frozen Food",
    "subcategory": "Paratha",
    "price": 1.99,
    "offer_price": null,
    "pack": "400G",
    "stock": "In Stock",
    "stock_qty": 1,
    "badge": "",
    "emoji": "cart",
    "description": "400G pack.",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgaYM2eKWbfv7LyKUss8MBpAj0pVRIxnhJJQ&s",
    "invoice_amount": 1.45,
    "invoice_qty": 1,
    "units_per_case": 1
  },
  {
    "id": 43,
    "sku": "INV-043",
    "name": "MOM MADE SPICY PARATHA 400G",
    "category": "Frozen Food",
    "subcategory": "Paratha",
    "price": 1.99,
    "offer_price": null,
    "pack": "400G",
    "stock": "In Stock",
    "stock_qty": 1,
    "badge": "",
    "emoji": "cart",
    "description": "400G pack.",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfOWI7xY-MKvDjnVnB7fulBQQhvPdpP7tNww&s",
    "invoice_amount": 1.45,
    "invoice_qty": 1,
    "units_per_case": 1
  },
  {
    "id": 44,
    "sku": "INV-044",
    "name": "SHANKAR VADAGAM PENTA WHEEL 200G",
    "category": "Grocery",
    "subcategory": "Vadagam & Vathal",
    "price": 1.19,
    "offer_price": null,
    "pack": "200G",
    "stock": "In Stock",
    "stock_qty": 1,
    "badge": "",
    "emoji": "cart",
    "description": "200G pack.",
    "image": "https://www.agnifoods.co.uk/pub/media/catalog/product/cache/ac27b5e23b258156220e993d45c667dc/s/h/shankar-vadagam-penta-wheel-200g.jpg",
    "invoice_amount": 1.58,
    "invoice_qty": 2,
    "units_per_case": 1
  },
  {
    "id": 45,
    "sku": "INV-045",
    "name": "SHANKAR CURD CHILLI 100G",
    "category": "Grocery",
    "subcategory": "Vadagam & Vathal",
    "price": 1.39,
    "offer_price": null,
    "pack": "100G",
    "stock": "In Stock",
    "stock_qty": 1,
    "badge": "",
    "emoji": "cart",
    "description": "100G pack.",
    "image": "https://bazaar-foods.co.uk/cdn/shop/products/shankar-curd-chillies-100g.jpg?v=1649321357",
    "invoice_amount": 1.98,
    "invoice_qty": 2,
    "units_per_case": 1
  },
  {
    "id": 46,
    "sku": "INV-046",
    "name": "AMARAVATHI IDLY RICE 10KG",
    "category": "Grocery",
    "subcategory": "Rice",
    "price": 12.99,
    "offer_price": null,
    "pack": "10KG",
    "stock": "In Stock",
    "stock_qty": 1,
    "badge": "",
    "emoji": "cart",
    "description": "10KG pack.",
    "image": "https://www.exoticestore.com/cdn/shop/files/AmaravathiRiceIdly10Kg_e40e3cc9-cf0f-4d6d-8db7-2ef940ed0134.jpg?v=1765275940",
    "invoice_amount": 8.75,
    "invoice_qty": 1,
    "units_per_case": 1
  },
  {
    "id": 47,
    "sku": "INV-047",
    "name": "SHANKAR PONNI RAW RICE 5KG",
    "category": "Grocery",
    "subcategory": "Rice",
    "price": 10.49,
    "offer_price": null,
    "pack": "5KG",
    "stock": "In Stock",
    "stock_qty": 1,
    "badge": "",
    "emoji": "cart",
    "description": "5KG pack.",
    "image": "https://www.sujash.co.uk/cdn/shop/files/Shankarponnirawrice5kg-1_1_720x.jpg?v=1695489935",
    "invoice_amount": 7.49,
    "invoice_qty": 1,
    "units_per_case": 1
  },
  {
    "id": 48,
    "sku": "INV-048",
    "name": "SHANKAR PAL VATHAL 200G",
    "category": "Grocery",
    "subcategory": "Vadagam & Vathal",
    "price": 1.99,
    "offer_price": null,
    "pack": "200G",
    "stock": "In Stock",
    "stock_qty": 1,
    "badge": "",
    "emoji": "cart",
    "description": "200G pack.",
    "image": "https://static.wixstatic.com/media/af3372_cb52bc06f40f444a9d542fa8fba3b935~mv2.jpg/v1/fill/w_479,h_468,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/af3372_cb52bc06f40f444a9d542fa8fba3b935~mv2.jpg",
    "invoice_amount": 2.58,
    "invoice_qty": 2,
    "units_per_case": 1
  },
  {
    "id": 49,
    "sku": "INV-049",
    "name": "SHANKAR KOTHAVARAI VATHAL 200G",
    "category": "Grocery",
    "subcategory": "Vadagam & Vathal",
    "price": 1.49,
    "offer_price": null,
    "pack": "200G",
    "stock": "In Stock",
    "stock_qty": 1,
    "badge": "",
    "emoji": "cart",
    "description": "200G pack.",
    "image": "https://krishnaslocal.com/wp-content/uploads/2023/02/Shankar-Kothavarai-Vathal-200g.webp.webp",
    "invoice_amount": 1.5,
    "invoice_qty": 2,
    "units_per_case": 1
  },
  {
    "id": 50,
    "sku": "INV-050",
    "name": "SHANKAR TAMARIND BAR 200G",
    "category": "Grocery",
    "subcategory": "Tamarind",
    "price": 0.99,
    "offer_price": null,
    "pack": "200G",
    "stock": "In Stock",
    "stock_qty": 1,
    "badge": "",
    "emoji": "cart",
    "description": "200G pack.",
    "image": "https://cambridgespices.co.uk/wp-content/uploads/2021/02/shankar-tamarind-200g.webp",
    "invoice_amount": 1.08,
    "invoice_qty": 3,
    "units_per_case": 1
  },
  {
    "id": 51,
    "sku": "INV-051",
    "name": "SHANKAR BLACK RICE KARUPPU KAVUNI RICE 1KG",
    "category": "Grocery",
    "subcategory": "Rice",
    "price": 6.49,
    "offer_price": null,
    "pack": "1KG",
    "stock": "In Stock",
    "stock_qty": 1,
    "badge": "",
    "emoji": "cart",
    "description": "1KG pack.",
    "image": "https://i.ebayimg.com/images/g/thUAAOSw4clmsu3g/s-l1200.jpg",
    "invoice_amount": 4.5,
    "invoice_qty": 1,
    "units_per_case": 1
  },
  {
    "id": 52,
    "sku": "INV-052",
    "name": "SHANKAR SESAME BAR 100G",
    "category": "Snacks",
    "subcategory": "Sweets & Bars",
    "price": 1.39,
    "offer_price": null,
    "pack": "100G",
    "stock": "In Stock",
    "stock_qty": 25,
    "badge": "",
    "emoji": "cart",
    "description": "100G pack.",
    "image": "https://allibhavan.com/cdn/shop/files/sankar-sesame-bar-100g-alli-bhavan-963071.jpg?v=1725544816&width=1080",
    "invoice_amount": 24.75,
    "invoice_qty": 1,
    "units_per_case": 25
  },
  {
    "id": 53,
    "sku": "INV-053",
    "name": "NIRU CHUNDAKKAI VATHAL 100G",
    "category": "Grocery",
    "subcategory": "Vadagam & Vathal",
    "price": 1.29,
    "offer_price": null,
    "pack": "100G",
    "stock": "In Stock",
    "stock_qty": 1,
    "badge": "",
    "emoji": "cart",
    "description": "100G pack.",
    "image": "https://m.media-amazon.com/images/I/61JybYCDBEL._AC_UF894,1000_QL80_.jpg",
    "invoice_amount": 3.25,
    "invoice_qty": 5,
    "units_per_case": 1
  },
  {
    "id": 54,
    "sku": "INV-054",
    "name": "NIRU CHARAKKU CURRY POWDER 225G",
    "category": "Grocery",
    "subcategory": "Masala & Spices",
    "price": 3.35,
    "offer_price": null,
    "pack": "225G",
    "stock": "In Stock",
    "stock_qty": 1,
    "badge": "",
    "emoji": "cart",
    "description": "225G pack.",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcIgAd2teOYypLfunDuywPjIRaGCl_5p8wBw&s",
    "invoice_amount": 4.78,
    "invoice_qty": 2,
    "units_per_case": 1
  },
  {
    "id": 55,
    "sku": "INV-055",
    "name": "SAPNA GINGER & GARLIC PASTE 1KG",
    "category": "Grocery",
    "subcategory": "Paste",
    "price": 2.99,
    "offer_price": null,
    "pack": "1KG",
    "stock": "In Stock",
    "stock_qty": 6,
    "badge": "",
    "emoji": "cart",
    "description": "1KG pack.",
    "image": "https://m.media-amazon.com/images/I/71m8AWPShwL._AC_UF894,1000_QL80_.jpg",
    "invoice_amount": 21.98,
    "invoice_qty": 2,
    "units_per_case": 6
  },
  {
    "id": 56,
    "sku": "INV-056",
    "name": "NIRU MAPILLAI SAMBA RICE 1KG",
    "category": "Grocery",
    "subcategory": "Rice",
    "price": 2.59,
    "offer_price": null,
    "pack": "1KG",
    "stock": "In Stock",
    "stock_qty": 20,
    "badge": "",
    "emoji": "cart",
    "description": "1KG pack.",
    "image": "https://i0.wp.com/uzhavuorganic.com/wp-content/uploads/2021/05/mapalai-samba-rice-online-chennai.jpg?fit=600%2C600&ssl=1",
    "invoice_amount": 36,
    "invoice_qty": 1,
    "units_per_case": 20
  },
  {
    "id": 57,
    "sku": "INV-057",
    "name": "KOKA CURRY FLAVOUR INSTANT NOODLES 85G",
    "category": "Noodles",
    "subcategory": "Instant Noodles",
    "price": 0.59,
    "offer_price": null,
    "pack": "85G",
    "stock": "In Stock",
    "stock_qty": 30,
    "badge": "",
    "emoji": "cart",
    "description": "85G pack.",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpVZJ_7w0fPA0le0wyV4qrKcii7NznT4NsDw&s",
    "invoice_amount": 10.99,
    "invoice_qty": 1,
    "units_per_case": 30
  },
  {
    "id": 58,
    "sku": "INV-058",
    "name": "JAIMIN PALAK CHAKLI 200G",
    "category": "Snacks",
    "subcategory": "Savoury Snacks",
    "price": 1.29,
    "offer_price": null,
    "pack": "200G",
    "stock": "In Stock",
    "stock_qty": 6,
    "badge": "",
    "emoji": "cart",
    "description": "200G pack.",
    "image": "https://bazaar-foods.co.uk/cdn/shop/products/jaimin-palak-chakli.jpg?v=1649248266",
    "invoice_amount": 5.45,
    "invoice_qty": 1,
    "units_per_case": 6
  },
  {
    "id": 59,
    "sku": "INV-059",
    "name": "JAIMIN CHANA DAL 200G",
    "category": "Snacks",
    "subcategory": "Savoury Snacks",
    "price": 1.29,
    "offer_price": null,
    "pack": "200G",
    "stock": "In Stock",
    "stock_qty": 6,
    "badge": "",
    "emoji": "cart",
    "description": "200G pack.",
    "image": "https://bazaar-foods.co.uk/cdn/shop/products/jaimin-chana-dal.jpg?v=1649247436",
    "invoice_amount": 5.45,
    "invoice_qty": 1,
    "units_per_case": 6
  },
  {
    "id": 60,
    "sku": "INV-060",
    "name": "KINGS GRAM FLOUR 100G",
    "category": "Grocery",
    "subcategory": "Flour & Atta",
    "price": 1.19,
    "offer_price": null,
    "pack": "100G",
    "stock": "In Stock",
    "stock_qty": 1,
    "badge": "",
    "emoji": "cart",
    "description": "100G pack.",
    "image": "https://www.smartbazaar.co.uk/wp-content/uploads/2020/10/Kings-Roasted-Gram-Pattani-100g.jpg",
    "invoice_amount": 2.4,
    "invoice_qty": 3,
    "units_per_case": 1
  },
  {
    "id": 61,
    "sku": "INV-061",
    "name": "KINGS CURRY POWDER 900G",
    "category": "Grocery",
    "subcategory": "Masala & Spices",
    "price": 8.99,
    "offer_price": null,
    "pack": "900G",
    "stock": "In Stock",
    "stock_qty": 24,
    "badge": "",
    "emoji": "cart",
    "description": "900G pack.",
    "image": "https://m.media-amazon.com/images/I/51P3fka5DAL._AC_UF894,1000_QL80_.jpg",
    "invoice_amount": 186,
    "invoice_qty": 1,
    "units_per_case": 24
  },
  {
    "id": 62,
    "sku": "INV-062",
    "name": "SHANKAR BHUNA CHANNA 300G",
    "category": "Snacks",
    "subcategory": "Roasted Snacks",
    "price": 1.82,
    "offer_price": null,
    "pack": "300G",
    "stock": "In Stock",
    "stock_qty": 1,
    "badge": "",
    "emoji": "cart",
    "description": "300G pack.",
    "image": "https://www.hariomatta.com/cdn/shop/files/bhunaaa.png?v=1753698666",
    "invoice_amount": 1.3,
    "invoice_qty": 1,
    "units_per_case": 1
  },
  {
    "id": 63,
    "sku": "INV-063",
    "name": "ROYAL PUNJAB ORANGE CANDY 100G",
    "category": "Snacks",
    "subcategory": "Sweets & Candy",
    "price": 0.99,
    "offer_price": null,
    "pack": "100G",
    "stock": "In Stock",
    "stock_qty": 12,
    "badge": "",
    "emoji": "cart",
    "description": "100G pack.",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTA6xu6n5vIFnOsOWyOXHiqUNHLiDHrnA9oQ&s",
    "invoice_amount": 6.75,
    "invoice_qty": 1,
    "units_per_case": 12
  },
  {
    "id": 64,
    "sku": "INV-064",
    "name": "NIRU COCONUT MILK TIN 400G",
    "category": "Grocery",
    "subcategory": "Coconut",
    "price": 1.49,
    "offer_price": null,
    "pack": "400G",
    "stock": "In Stock",
    "stock_qty": 12,
    "badge": "",
    "emoji": "cart",
    "description": "400G pack.",
    "image": "https://m.media-amazon.com/images/I/51tbaCXWgOL.jpg",
    "invoice_amount": 10.8,
    "invoice_qty": 1,
    "units_per_case": 12
  },
  {
    "id": 65,
    "sku": "INV-065",
    "name": "UFC COCONUT WATER 1L",
    "category": "Drinks",
    "subcategory": "Coconut Water",
    "price": 1.98,
    "offer_price": null,
    "pack": "1L",
    "stock": "In Stock",
    "stock_qty": 6,
    "badge": "",
    "emoji": "cart",
    "description": "1L pack.",
    "image": "https://digitalcontent.api.tesco.com/v2/media/ghs/919a9051-726b-4d5e-85ca-a3b7e1e12664/5a1e98ff-74a7-4c81-b87a-b80df7aa3997_1310399291.jpeg",
    "invoice_amount": 8.5,
    "invoice_qty": 1,
    "units_per_case": 6
  },
  {
    "id": 66,
    "sku": "INV-066",
    "name": "SHANKAR URID DHAL WHOLE WHITE 2KG",
    "category": "Grocery",
    "subcategory": "Dals & Pulses",
    "price": 5.49,
    "offer_price": null,
    "pack": "2KG",
    "stock": "In Stock",
    "stock_qty": 6,
    "badge": "",
    "emoji": "cart",
    "description": "2KG pack.",
    "image": "https://cdn.dotpe.in/longtail/store-items/8372269/9KEUZ5m6.webp",
    "invoice_amount": 22,
    "invoice_qty": 1,
    "units_per_case": 6
  },
  {
    "id": 67,
    "sku": "INV-067",
    "name": "FAIRY PROFESSIONAL CLASSIC LIQUID 5L",
    "category": "Household",
    "subcategory": "Cleaning",
    "price": 15.39,
    "offer_price": null,
    "pack": "5L",
    "stock": "In Stock",
    "stock_qty": 1,
    "badge": "",
    "emoji": "cart",
    "description": "5L pack.",
    "image": "https://www.outofeden.co.uk/cdn/shop/files/5051-5FairyProfessionalWashing-UpLiquid5L.webp?crop=center&height=1200&v=1752053278&width=1200",
    "invoice_amount": 10.99,
    "invoice_qty": 1,
    "units_per_case": 1
  },
  {
    "id": 68,
    "sku": "INV-068",
    "name": "FU XING QUICK COOKING EGG NOODLE 400G",
    "category": "Noodles",
    "subcategory": "Egg Noodles",
    "price": 1.39,
    "offer_price": null,
    "pack": "400G",
    "stock": "In Stock",
    "stock_qty": 1,
    "badge": "",
    "emoji": "cart",
    "description": "400G pack.",
    "image": "https://img-va.myshopline.com/image/store/1708619866655/FUXING-Quick-Cooking-Egg-Noodles-400g.jpeg?w=225&h=225",
    "invoice_amount": 0.99,
    "invoice_qty": 1,
    "units_per_case": 1
  },
  {
    "id": 69,
    "sku": "INV-069",
    "name": "KIAT ROSE SYRUP 750ML",
    "category": "Drinks",
    "subcategory": "Syrup",
    "price": 2.99,
    "offer_price": null,
    "pack": "750ML",
    "stock": "In Stock",
    "stock_qty": 12,
    "badge": "",
    "emoji": "cart",
    "description": "750ML pack.",
    "image": "https://m.media-amazon.com/images/I/61e7hvttiXL.jpg",
    "invoice_amount": 24.95,
    "invoice_qty": 1,
    "units_per_case": 12
  },
  {
    "id": 70,
    "sku": "INV-070",
    "name": "BRU GREEN LABEL 500G",
    "category": "Grocery",
    "subcategory": "Tea & Coffee",
    "price": 5.99,
    "offer_price": null,
    "pack": "500G",
    "stock": "In Stock",
    "stock_qty": 1,
    "badge": "",
    "emoji": "cart",
    "description": "500G pack.",
    "image": "https://www.sujash.co.uk/cdn/shop/files/BruGreenlabel-1.jpg?v=1727371866",
    "invoice_amount": 4,
    "invoice_qty": 1,
    "units_per_case": 1
  },
  {
    "id": 71,
    "sku": "INV-071",
    "name": "CHING'S SECRET SCHEZWAN CHUTNEY 600G",
    "category": "Grocery",
    "subcategory": "Chutney",
    "price": 4.99,
    "offer_price": null,
    "pack": "600G",
    "stock": "In Stock",
    "stock_qty": 1,
    "badge": "",
    "emoji": "cart",
    "description": "600G pack.",
    "image": "https://bazaar-foods.co.uk/cdn/shop/files/chings-schezwan-chutney.jpg?v=1696682564",
    "invoice_amount": 2.99,
    "invoice_qty": 1,
    "units_per_case": 1
  },
  {
    "id": 72,
    "sku": "INV-072",
    "name": "MD SANDAL 106G",
    "category": "Grocery",
    "subcategory": "Incense",
    "price": 1.89,
    "offer_price": null,
    "pack": "106G",
    "stock": "In Stock",
    "stock_qty": 6,
    "badge": "",
    "emoji": "cart",
    "description": "106G pack.",
    "image": "https://www.silkrute.co.uk/images/detailed/2894/31soCFO5DOL.jpg",
    "invoice_amount": 7,
    "invoice_qty": 1,
    "units_per_case": 6
  },
  {
    "id": 73,
    "sku": "INV-073",
    "name": "MOM'S MAGIC RICH BUTTER 750G",
    "category": "Grocery",
    "subcategory": "Biscuits",
    "price": 2.79,
    "offer_price": null,
    "pack": "750G",
    "stock": "In Stock",
    "stock_qty": 1,
    "badge": "",
    "emoji": "cart",
    "description": "750G pack.",
    "image": "https://m.media-amazon.com/images/I/81M7Cb8bv6L.jpg",
    "invoice_amount": 1.99,
    "invoice_qty": 1,
    "units_per_case": 1
  },
  {
    "id": 74,
    "sku": "INV-074",
    "name": "SHANKAR MANATHAKKALI VATHAL 200G",
    "category": "Grocery",
    "subcategory": "Vadagam & Vathal",
    "price": 1.99,
    "offer_price": null,
    "pack": "200G",
    "stock": "In Stock",
    "stock_qty": 1,
    "badge": "",
    "emoji": "cart",
    "description": "200G pack.",
    "image": "https://allibhavan.com/cdn/shop/files/shankar-manathakkali-vathal-200g-alli-bhavan-882319.png?v=1722839893",
    "invoice_amount": 2.18,
    "invoice_qty": 2,
    "units_per_case": 1
  },
  {
    "id": 75,
    "sku": "INV-075",
    "name": "SHANKAR VADAGAM COLOUR TUBE 200G",
    "category": "Grocery",
    "subcategory": "Vadagam & Vathal",
    "price": 1.49,
    "offer_price": null,
    "pack": "200G",
    "stock": "In Stock",
    "stock_qty": 1,
    "badge": "",
    "emoji": "cart",
    "description": "200G pack.",
    "image": "https://www.rastoo.com/cdn/shop/files/1_d2037719-1efa-4dce-a71f-927ea73d0929.png?crop=center&height=495&v=1693825317&width=500",
    "invoice_amount": 2.25,
    "invoice_qty": 3,
    "units_per_case": 1
  },
  {
    "id": 76,
    "sku": "INV-076",
    "name": "SHANKAR VADAGAM STAR 200G",
    "category": "Grocery",
    "subcategory": "Vadagam & Vathal",
    "price": 1.49,
    "offer_price": null,
    "pack": "200G",
    "stock": "In Stock",
    "stock_qty": 1,
    "badge": "",
    "emoji": "cart",
    "description": "200G pack.",
    "image": "https://www.rastoo.com/cdn/shop/files/8_028a2795-2801-4d55-ba76-162bb5af94ad.png?v=1693825573",
    "invoice_amount": 1.5,
    "invoice_qty": 2,
    "units_per_case": 1
  },
  {
    "id": 77,
    "sku": "INV-077",
    "name": "SHANKAR POTATO VADAGAM 200G",
    "category": "Grocery",
    "subcategory": "Vadagam & Vathal",
    "price": 1.49,
    "offer_price": null,
    "pack": "200G",
    "stock": "In Stock",
    "stock_qty": 1,
    "badge": "",
    "emoji": "cart",
    "description": "200G pack.",
    "image": "https://www.rastoo.com/cdn/shop/files/5_d4297951-9304-4747-a7dc-ac1ec996f826.png?v=1693825739",
    "invoice_amount": 1.5,
    "invoice_qty": 2,
    "units_per_case": 1
  },
  {
    "id": 78,
    "sku": "INV-078",
    "name": "SHANKAR RED RICE FLAKES 1KG",
    "category": "Grocery",
    "subcategory": "Rice & Flakes",
    "price": 2.99,
    "offer_price": null,
    "pack": "1KG",
    "stock": "In Stock",
    "stock_qty": 10,
    "badge": "",
    "emoji": "cart",
    "description": "1KG pack.",
    "image": "https://asianbuy.co.uk/wp/wp-content/uploads/2021/05/Shankar-Red-Rice-Flakes-400g.png",
    "invoice_amount": 20,
    "invoice_qty": 1,
    "units_per_case": 10
  },
  {
    "id": 79,
    "sku": "INV-079",
    "name": "SHANKAR GINGELLY OIL GLASS 750ML",
    "category": "Grocery",
    "subcategory": "Oil & Ghee",
    "price": 3.99,
    "offer_price": null,
    "pack": "750ML",
    "stock": "In Stock",
    "stock_qty": 75,
    "badge": "",
    "emoji": "cart",
    "description": "750ML pack.",
    "image": "https://i1.wp.com/www.ukceylon.com/wp-content/uploads/2021/10/shankar-gingelly-oil-sesame-oil-750ml.jpg?fit=1080%2C1080&ssl=1?v=1637700182",
    "invoice_amount": 224.25,
    "invoice_qty": 5,
    "units_per_case": 15
  },
  {
    "id": 80,
    "sku": "INV-080",
    "name": "AACHI MUTTON MASALA 100G",
    "category": "Grocery",
    "subcategory": "Aachi Masala",
    "price": 1.49,
    "offer_price": null,
    "pack": "100G",
    "stock": "In Stock",
    "stock_qty": 10,
    "badge": "",
    "emoji": "cart",
    "description": "100G pack.",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNHSYRIlO7P7ryD6temaJCuNUx39P14iyTzw&s",
    "invoice_amount": 10.49,
    "invoice_qty": 1,
    "units_per_case": 10
  },
  {
    "id": 81,
    "sku": "INV-081",
    "name": "AACHI FISH CURRY MASALA 100G",
    "category": "Grocery",
    "subcategory": "Aachi Masala",
    "price": 1.47,
    "offer_price": null,
    "pack": "100G",
    "stock": "In Stock",
    "stock_qty": 10,
    "badge": "",
    "emoji": "cart",
    "description": "100G pack.",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSi-Ifxkh_BcZyvefubzBj2tFxg-NOLJoZtqQ&s",
    "invoice_amount": 10.49,
    "invoice_qty": 1,
    "units_per_case": 10
  },
  {
    "id": 82,
    "sku": "INV-082",
    "name": "AACHI CHICKEN MASALA 100G",
    "category": "Grocery",
    "subcategory": "Aachi Masala",
    "price": 1.49,
    "offer_price": null,
    "pack": "100G",
    "stock": "In Stock",
    "stock_qty": 10,
    "badge": "",
    "emoji": "cart",
    "description": "100G pack.",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4MyFmyUUqD7j8h3pKhxNB0DbP2GSEJlwp7Q&s",
    "invoice_amount": 10.49,
    "invoice_qty": 1,
    "units_per_case": 10
  },
  {
    "id": 83,
    "sku": "INV-083",
    "name": "AACHI CHICKEN TIKKA MASALA 100G",
    "category": "Grocery",
    "subcategory": "Aachi Masala",
    "price": 1.59,
    "offer_price": null,
    "pack": "100G",
    "stock": "In Stock",
    "stock_qty": 10,
    "badge": "",
    "emoji": "cart",
    "description": "100G pack.",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYfzo7nZBoKQ0--WZl0Ifj8rqtB8LwBwVr-Q&s",
    "invoice_amount": 11.39,
    "invoice_qty": 1,
    "units_per_case": 10
  },
  {
    "id": 84,
    "sku": "INV-084",
    "name": "AACHI BIRYANI RICE PASTE 300G",
    "category": "Grocery",
    "subcategory": "Aachi Paste",
    "price": 2.99,
    "offer_price": null,
    "pack": "300G",
    "stock": "In Stock",
    "stock_qty": 6,
    "badge": "",
    "emoji": "cart",
    "description": "300G pack.",
    "image": "https://allibhavan.com/cdn/shop/files/aachi-biryani-rice-paste-300g-alli-bhavan-322458.png?v=1720087835",
    "invoice_amount": 11.39,
    "invoice_qty": 1,
    "units_per_case": 6
  },
  {
    "id": 85,
    "sku": "INV-085",
    "name": "AACHI FISH FRY MASALA 100G",
    "category": "Grocery",
    "subcategory": "Aachi Masala",
    "price": 1.65,
    "offer_price": null,
    "pack": "100G",
    "stock": "In Stock",
    "stock_qty": 10,
    "badge": "",
    "emoji": "cart",
    "description": "100G pack.",
    "image": "https://cambridgespices.co.uk/wp-content/uploads/2021/02/aachi-fish-fry.jpg",
    "invoice_amount": 11.75,
    "invoice_qty": 1,
    "units_per_case": 10
  },
  {
    "id": 86,
    "sku": "INV-086",
    "name": "AACHI MADRAS SAMBAR POWDER 100G",
    "category": "Grocery",
    "subcategory": "Aachi Masala",
    "price": 1.49,
    "offer_price": null,
    "pack": "100G",
    "stock": "In Stock",
    "stock_qty": 10,
    "badge": "",
    "emoji": "cart",
    "description": "100G pack.",
    "image": "https://rukmini1.flixcart.com/image/300/300/xif0q/spice-masala/d/n/z/-original-imagu7ybsjsfnqqn.jpeg",
    "invoice_amount": 10.49,
    "invoice_qty": 1,
    "units_per_case": 10
  },
  {
    "id": 87,
    "sku": "INV-087",
    "name": "AACHI CHUKKU MALLI KAPPI POWDER 100G",
    "category": "Grocery",
    "subcategory": "Aachi Coffee",
    "price": 1.69,
    "offer_price": null,
    "pack": "100G",
    "stock": "In Stock",
    "stock_qty": 10,
    "badge": "",
    "emoji": "cart",
    "description": "100G pack.",
    "image": "https://rukmini1.flixcart.com/image/300/300/xif0q/ready-mix/q/e/j/100-sukku-malli-kaapi-powder-1-breakfast-mix-aachi-original-imagxutdxsxhqnae.jpeg",
    "invoice_amount": 11.49,
    "invoice_qty": 1,
    "units_per_case": 10
  },
  {
    "id": 88,
    "sku": "INV-088",
    "name": "AACHI CHICKEN MANCHURIAN MASALA 100G",
    "category": "Grocery",
    "subcategory": "Aachi Masala",
    "price": 1.69,
    "offer_price": null,
    "pack": "100G",
    "stock": "In Stock",
    "stock_qty": 10,
    "badge": "",
    "emoji": "cart",
    "description": "100G pack.",
    "image": "https://jnsfoods.se/wp-content/uploads/2025/06/550x804.jpg",
    "invoice_amount": 11.99,
    "invoice_qty": 1,
    "units_per_case": 10
  },
  {
    "id": 89,
    "sku": "INV-089",
    "name": "PILLSBURY CHAKKI ATTA 10KG",
    "category": "Grocery",
    "subcategory": "Flour & Atta",
    "price": 15.99,
    "offer_price": null,
    "pack": "10KG",
    "stock": "In Stock",
    "stock_qty": 1,
    "badge": "",
    "emoji": "cart",
    "description": "10KG pack.",
    "image": "https://m.media-amazon.com/images/I/71zIM77PjUL._AC_UF894,1000_QL80_.jpg",
    "invoice_amount": 11.49,
    "invoice_qty": 1,
    "units_per_case": 1
  },
  {
    "id": 90,
    "sku": "INV-090",
    "name": "ANIL ROASTED SHORT VERMICELLI 180G",
    "category": "Grocery",
    "subcategory": "Vermicelli",
    "price": 0.69,
    "offer_price": null,
    "pack": "180G",
    "stock": "In Stock",
    "stock_qty": 20,
    "badge": "",
    "emoji": "cart",
    "description": "180G pack.",
    "image": "https://m.media-amazon.com/images/I/61nT4BDLtwL.jpg",
    "invoice_amount": 9.8,
    "invoice_qty": 1,
    "units_per_case": 20
  }
];
